services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}